services:

  doc-emb:
    image: optimum-onnx-serving-cpu:0.1.2
    volumes:
     - /home/miftah/Downloads/job_application/mekari/review_bot/tinybert:/app/models
    ports:
      - 8899:80
    environment:
      - LOG_DIR=/app/logs
      - ONNX_MODEL_NAME=${ONNX_MODEL_NAME:-model.onnx}
      - MAX_SEQ_LENGTH=${MAX_SEQ_LENGTH:-256}
    command: uvicorn serve:app --host 0.0.0.0 --port 80 --timeout-keep-alive 1000
